# Linear Algebra

In [3]:
# Imports
import numpy as np

## Scalars, Vectors and Matrices

### Scalars
- A single number

### Vectors
- A 1D array of numbers, where each element is identified by a single index

### Matrix
- A 2D array of numbers, where a single element is identified by two indexes instead of one

![title](images/scalars_vector_matrix.png)

# Addition and Subtraction
![title](images/addition_and_subtraction.png)

In [16]:
A = np.array([[3, 8],[4, 6]])
B = np.array([[4, 0], [1, -9]])

print(A + B)
print(A - B)

[[ 7  8]
 [ 5 -3]]
[[-1  8]
 [ 3 15]]


# Multiply Matrixes by Scalar
![title](images/multiply_with_scalar.png)

# Matrix Multiplication
![title](images/dot_product.png)

## Dimension of the result matrix
- Soviele Zeilen wie die Matrix A
- Soviele Spalten wie die Matrix B



In [14]:
A = np.array([[1, 2, 3],[4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])

print(np.matmul(A,B))

[[ 58  64]
 [139 154]]
[[ 58  64]
 [139 154]]


In [15]:
# Welches Resultat ergibt B*A?
print(np.matmul(B,A))

[[ 39  54  69]
 [ 49  68  87]
 [ 59  82 105]]


# Transpose a matrix